// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDm2TN6iB-EiobPj0juzJt1-rdZ_1KbkD0',
    appId: '1:17411400236:web:7b02292953486b3e19e789',
    messagingSenderId: '17411400236',
    projectId: 'travel-buddy-3138c',
    authDomain: 'travel-buddy-3138c.firebaseapp.com',
    storageBucket: 'travel-buddy-3138c.appspot.com',
    measurementId: 'G-ZEHS7ECRE4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBA3dy9hTOiCO7x2VZTqTA2U9ioH4jYfIA',
    appId: '1:17411400236:android:6bca602e011eee0a19e789',
    messagingSenderId: '17411400236',
    projectId: 'travel-buddy-3138c',
    storageBucket: 'travel-buddy-3138c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpx8PSdU0LZcA7AQNDBq3v2q8RrrkoEk4',
    appId: '1:17411400236:ios:7f9cbc9b5413825f19e789',
    messagingSenderId: '17411400236',
    projectId: 'travel-buddy-3138c',
    storageBucket: 'travel-buddy-3138c.appspot.com',
    iosBundleId: 'com.example.travelBuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpx8PSdU0LZcA7AQNDBq3v2q8RrrkoEk4',
    appId: '1:17411400236:ios:7f9cbc9b5413825f19e789',
    messagingSenderId: '17411400236',
    projectId: 'travel-buddy-3138c',
    storageBucket: 'travel-buddy-3138c.appspot.com',
    iosBundleId: 'com.example.travelBuddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDm2TN6iB-EiobPj0juzJt1-rdZ_1KbkD0',
    appId: '1:17411400236:web:ade0b9e2d667fa0319e789',
    messagingSenderId: '17411400236',
    projectId: 'travel-buddy-3138c',
    authDomain: 'travel-buddy-3138c.firebaseapp.com',
    storageBucket: 'travel-buddy-3138c.appspot.com',
    measurementId: 'G-CM3EBS9HSC',
  );
}
